### PR TITLE
[GT-185] Update logging in test_crypto

### LINKED ISSUE #244: outdated logging necessity comment
These lines haven't been touched since 11 years ago (when they were written I think).
So is the logging necessary?

https://github.com/apel/ssm/blob/dev/test/test_crypto.py#L20-L22

### PR DESCRIPTION
**Pull request by rowan04**
- removes old comment
- gets rid of logging.getLogger('SSM')

resolves #244

test output:
```
[root@host-172-16-105-234 test]# python test_crypto.py
Generating a 2048 bit RSA private key
................................+++
................................................................+++
writing new private key to '/tmp/test.key'
-----
.Generating a 2048 bit RSA private key
..+++
............................................................................+++
writing new private key to '/tmp/test.key'
-----
ERROR:ssm.crypto:unable to load certificate
140315647899536:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:707:Expecting: TRUSTED CERTIFICATE

.Generating a 2048 bit RSA private key
.........................................+++
...........................................................................................+++
writing new private key to '/tmp/test.key'
-----
ERROR:ssm.crypto:unable to load certificate
140567456802704:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:707:Expecting: TRUSTED CERTIFICATE

ERROR:ssm.crypto:unable to load key
140295188965264:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:707:Expecting: ANY PRIVATE KEY

.Generating a 2048 bit RSA private key
................................................................................................................................................+++
........................................................................................................................................+++
writing new private key to '/tmp/test.key'
-----
ERROR:ssm.crypto:Could not find cert or key file: [Errno 2] No such file or directory: 'hello'
ERROR:ssm.crypto:Could not find cert or key file: [Errno 2] No such file or directory: 'k'
ERROR:ssm.crypto:Could not find cert or key file: [Errno 2] No such file or directory: 'c'
.Generating a 2048 bit RSA private key
.+++
.......................................................................+++
writing new private key to '/tmp/test.key'
-----
.Generating a 2048 bit RSA private key
....................+++
...+++
writing new private key to '/tmp/test.key'
-----
.Generating a 2048 bit RSA private key
.+++
......+++
writing new private key to '/tmp/test.key'
-----
ERROR:ssm.crypto:unable to load certificate
140579938973584:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:707:Expecting: TRUSTED CERTIFICATE

ERROR:ssm.crypto:unable to load certificate
140532835903376:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:707:Expecting: TRUSTED CERTIFICATE

.Generating a 2048 bit RSA private key
..............+++
........................................+++
writing new private key to '/tmp/test.key'
-----
.Generating a 2048 bit RSA private key
.......+++
................................................................................................................+++
writing new private key to '/tmp/test.key'
-----
.Generating a 2048 bit RSA private key
......................................................................+++
..........................+++
writing new private key to '/tmp/test.key'
-----
.Generating a 2048 bit RSA private key
.....................................................+++
.......................................................................................................................................+++
writing new private key to '/tmp/test.key'
-----
ERROR:ssm.crypto:Error reading S/MIME message
139928187541392:error:0D0D40D1:asn1 encoding routines:SMIME_read_ASN1:no content type:asn_mime.c:440:

ERROR:ssm.crypto:unable to load PKCS7 object
140338298214288:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:707:Expecting: PKCS7

ERROR:ssm.crypto:unable to load certificate
139704674850704:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:707:Expecting: TRUSTED CERTIFICATE

WARNING:ssm.crypto:Certificate verification:
ERROR:ssm.crypto:Error reading S/MIME message
140515806496656:error:0D0D40D1:asn1 encoding routines:SMIME_read_ASN1:no content type:asn_mime.c:440:

ERROR:ssm.crypto:unable to load PKCS7 object
139981541640080:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:707:Expecting: PKCS7

ERROR:ssm.crypto:unable to load certificate
140001239017360:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:707:Expecting: TRUSTED CERTIFICATE

WARNING:ssm.crypto:Certificate verification:
.Generating a 2048 bit RSA private key
.................+++
............................+++
writing new private key to '/tmp/test.key'
-----
WARNING:ssm.crypto:Certificate verification: stdin: C = UK, O = STFC, OU = SC, CN = Test Cert
error 18 at 0 depth lookup:self signed certificate
OK

ERROR:ssm.crypto:unable to load certificate
140181163296656:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:707:Expecting: TRUSTED CERTIFICATE

WARNING:ssm.crypto:Certificate verification:
WARNING:ssm.crypto:Certificate verification: stdin: C = UK, O = STFC, OU = SC, CN = Test Cert
error 3 at 0 depth lookup:unable to get certificate CRL

.
----------------------------------------------------------------------
Ran 12 tests in 1.573s

OK
```

### CODE REVIEW

**Comment by rowan04** [comment]
With no logging:
```
[root@host-172-16-105-234 test]# python test_crypto.py
Generating a 2048 bit RSA private key
......................................................................+++
................................................................+++
writing new private key to '/tmp/test.key'
-----
.Generating a 2048 bit RSA private key
..............................................+++
..................+++
writing new private key to '/tmp/test.key'
-----
No handlers could be found for logger "ssm.crypto"
.Generating a 2048 bit RSA private key
....+++
.........+++
writing new private key to '/tmp/test.key'
-----
.Generating a 2048 bit RSA private key
...........+++
............................................................+++
writing new private key to '/tmp/test.key'
-----
.Generating a 2048 bit RSA private key
.................................+++
.....+++
writing new private key to '/tmp/test.key'
-----
.Generating a 2048 bit RSA private key
.............................................................+++
..................................+++
writing new private key to '/tmp/test.key'
-----
.Generating a 2048 bit RSA private key
...............................................................................+++
.......+++
writing new private key to '/tmp/test.key'
-----
.Generating a 2048 bit RSA private key
.................................................................................................+++
.................................................+++
writing new private key to '/tmp/test.key'
-----
.Generating a 2048 bit RSA private key
........+++
..+++
writing new private key to '/tmp/test.key'
-----
.Generating a 2048 bit RSA private key
.............................+++
...+++
writing new private key to '/tmp/test.key'
-----
.Generating a 2048 bit RSA private key
......................................................................................................................................+++
...................................................................+++
writing new private key to '/tmp/test.key'
-----
.Generating a 2048 bit RSA private key
...................+++
............................................+++
writing new private key to '/tmp/test.key'
-----
.
----------------------------------------------------------------------
Ran 12 tests in 1.366s

OK

```

**Comment by rowan04** [comment]
Here is the link to a diffchecker comparing the original test output (using `log = logging.getlogger('ssm')`) and with that line removed:
https://www.diffchecker.com/AFNWfrAY/

and you can clealry see without a diffchecker the differences between these two and the output with no logging at all

**Comment by rowan04** [comment]
> Here is the link to a diffchecker comparing the original test output (using `log = logging.getlogger('ssm')`) and with that line removed: https://www.diffchecker.com/AFNWfrAY/
> 
> and you can clealry see without a diffchecker the differences between these two and the output with no logging at all

there is no meaningful difference between the outputs with the two different logging setups, and the output without logging lacks information

**Comment by rowan04** [comment]
reabsed onto latest dev

**Review by tofu-rocketry — APPROVED** [review]

**Comment by tofu-rocketry** [comment]
> Here is the link to a diffchecker comparing the original test output (using `log = logging.getlogger('ssm')`) and with that line removed: https://www.diffchecker.com/AFNWfrAY/
> 
> and you can clealry see without a diffchecker the differences between these two and the output with no logging at all

The Diffchecker view is useful. Thanks for that.

**Pull request merged**
